name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "format"
            java: 8
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - shell: bash
      run: |
        case ${{ matrix.name }} in
          "format")
            sbt -v scalafmtSbt "+ scalafmtAll"
            git diff --exit-code
            ;;
          "test-cross")
            sbt -v "project core" "testPartial 3 ${{matrix.test_index}}"
            ;;
          "scripted")
            sbt -v "+ publishLocal" "sbt-plugin/scripted wartremover/*${{matrix.test_index}}of2"
            ;;
          "inspector")
            sbt -J-Xmx7G -v '++ 3.2.2!' inspector/test
            ;;
          "test")
            sbt -v test
            ;;
          *)
            echo "unknown job"
            exit 1
        esac
    - uses: reviewdog/action-setup@8f2ec89e6b467ca9175527d2a1641bbd0c05783b # v1.0.3
      if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
      with:
        reviewdog_version: v0.14.0
    - run: reviewdog -version
      if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
    - uses: reviewdog/action-suggester@8f83d27e749053b2029600995c115026a010408e # v1.6.0
      if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tool_name: scalafmt
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
