name: ci
on:
  push:
jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        java: [8, 17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - shell: bash
      run: sbt core/testAll '++ 2.12.15!' test
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
