name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "format"
            java: 8
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - shell: bash
      run: |
        case ${{ matrix.name }} in
          "format")
            sbt -v scalafmtSbt "+ scalafmtAll"
            git diff --exit-code
            ;;
          "test-cross")
            sbt -v "project core" "testPartial 3 ${{matrix.test_index}}"
            ;;
          "scripted")
            sbt -v "+ publishLocal" "sbt-plugin/scripted wartremover/*${{matrix.test_index}}of2"
            ;;
          "inspector")
            sbt -J-Xmx7G -v '++ 3.2.2!' inspector/test
            ;;
          "test")
            sbt -v test
            ;;
          *)
            echo "unknown job"
            exit 1
        esac
    - if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
      run: |
        REVIEWDOG_VERSION="0.14.1"
        FILE_NAME="reviewdog_${REVIEWDOG_VERSION}_Linux_x86_64"
        wget -q https://github.com/reviewdog/reviewdog/releases/download/v${REVIEWDOG_VERSION}/${FILE_NAME}.tar.gz &&
        gunzip ${FILE_NAME}.tar.gz &&
        tar -xf ${FILE_NAME}.tar &&
        chmod +x ./reviewdog &&
        echo "${PWD}" >> $GITHUB_PATH
    - run: reviewdog -version
      if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
    - if: ${{ (github.event_name == 'pull_request') && failure() && matrix.name == 'format' }}
      run: |
        export INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export INPUT_TOOL_NAME="scalafmt"
        wget https://raw.githubusercontent.com/reviewdog/action-suggester/8f83d27e749053b2029600995c115026a010408e/script.sh -O - | sh
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
