name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    timeout-minutes: 100
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - shell: bash
      run: sbt -v "+ publishLocal" "sbt-plugin/scripted"
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
