name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 7 * * *'
jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - java: 17
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - shell: bash
      run: sbt -v "core/run com.typesafe.akka akka-actor 2.6.19"
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
